apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::870542455064:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-27O0ZJH2S6CI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::870542455064:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-01T19:43:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1736"
  uid: 0acc22b8-7acf-495b-8ea0-a70933c4aee1
